### PR TITLE
Added T20 Cricket Dataset

### PR DESCRIPTION
**Pull request by MihirRajeshPanchal**
This pull request solves issue : #2

### CODE REVIEW

**Comment by yonomitt** [comment]
@MihirRajeshPanchal Thanks for your contribution! Before we can accept this, could you please add a README.md for the T20 Cricket Dataset under its folder?

**Comment by MihirRajeshPanchal** [comment]
Sure @yonomitt

**Comment by MihirRajeshPanchal** [comment]
@yonomitt I have added the readme file in the commit : https://github.com/DagsHub/open-source-ml-datasets/pull/1/commits/71489a10492acd6e8a6ca761852c3bd67bb00c93

**Comment by yonomitt** [comment]
Hi @MihirRajeshPanchal, I just realized that you had added the data directly to your fork of the **open-source-ml-datasets**. What we're looking for is:

1. Create a Dagshub repo for the dataset
2. Have your (this) PR add a folder for the dataset with a README.md
3. The README.md should point to the DagsHub repo with the data

As an example, checkout the repo we created for Audio datasets last year: https://dagshub.com/DagsHub/audio-datasets

So to accept this PR, please move the data to a new DagsHub repo and update the README to point to that repo.

Thanks!

**Pull request closed without merging**
